version:  '3.2'

services:

    key-value:
        image: "redis"
        networks:
          - nosql
        ports:
          - 6379:6379  

    column:
        image: "cassandra"
        networks:
          - nosql
        ports:
          - 9042:9042

    document:
        image: "mongo:latest"
        networks:
          - nosql
        ports:
          - 27017:27017

    graph:
        image: "neo4j"
        networks:
          - nosql
        ports:
          - 7474:7474
          - 7687:7687


networks:
    nosql: